/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// Blue LED blink GPIOD15 on AHB1

	// AHB1 and GPIOD Mode and Output register address + offset
	uint32_t *pClkCtrlReg = (uint32_t*) (0x40023800 + 0x30),	// RCC_AHB1ENR
			*pPortDModeReg = (uint32_t*) (0x40020C00 + 0x00),	// GPIOx_MODER
			*pPortDOutReg = (uint32_t*) (0x40020C00 + 0x14);	// GPIOx_ODR

	// Enabling clock on Port D (SET 3rd bit position to 1 in RCC_AHB1ENR)
	*pClkCtrlReg |= 1 << 3;

	// Clearing port D15 for rewrite (CLEAR 31st and 30th bit position to 0 in GPIOx_MODER)
	*pPortDModeReg &= ~(3 << 30);
	// Setting port D15 mode to general purpose output (SET 31st and 30th bit position to 01 in GPIOx_MODER)
	*pPortDModeReg |= 1 << 30;

	/* Loop Delay */
	while(1) {
		// Setting port D15 output to 1 (SET 15th bit position to 1 in GPIOx_ODR)
		*pPortDOutReg |= 1 << 15;

		for(uint32_t i = 0; i < 300000; i++); // traps processor in a loop that executes 300k times

		// Turn off LED / CLEAR
		*pPortDOutReg &= ~(1 << 15);

		for(uint32_t i = 0; i < 300000; i++); // traps processor in a loop that executes 300k times
	}
}
