/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	/*-----------------------------------------------------------------------
	 * One of the LEDs is connected to GPIOD12
	 * From STM32F40x reference manual
	 * 		-> Memory and bus architecture
	 * 		-> Memory map
	 * Base address of RCC peripheral registers (RCC_AHB1ENR)	= 0x4002 3800
	 * Base address of GPIOD peripherals						= 0x4002 0C00
	 *-----------------------------------------------------------------------
	 * 		-> Reset and clock control
	 * 		-> RCC registers
	 * 		-> RCC AHBx peripheral clock register
	 * 			(refer to data sheet internal architecture
	 * 			to figure out which AHB desired peripheral
	 * 			is connected to)
	 * AHB1 peripheral clock register for GPIOD is located in
	 * the 3rd bit field. Set bit field to 1 to start clock.
	 * Address offset											= 0x30
	 * Reset value												= 0x00100000
	 *-----------------------------------------------------------------------
	 * 		-> General-purpose I/O's (GPIO)
	 * 		-> GPIO register
	 * 		-> GPIO port mode register
	 * GPIO port D12 is located in 24th and 25th bit field.
	 * Write 01 into bit fields to configure into output mode.
	 * Address offset											= 0x00
	 * Reset value depends on which port D is 					= 0x00000000
	 *-----------------------------------------------------------------------
	 * 		-> GPIO port output data register
	 * GPIOD12 write 1 for high, 0 for low.
	 * Address offset											= 0x14
	 * Reset value												= 0x00000000
	 *-----------------------------------------------------------------------*/

    uint32_t* pClkCtrlReg = (uint32_t*) (0x40023800 + 0x30);		// (RCC_AHB1ENR)
    uint32_t* pPortDModeReg = (uint32_t*) (0x40020C00 + 0x00);		// (GPIOx_MODER D12)
    uint32_t* pPortDOutReg = (uint32_t*) (0x40020C00 + 0x14);		// (GPIOx_ODR)

    /* To SET the bit at the 3rd bit positions for RCC_AHB1ENR, read register content to
     * determine mask value, then write the result back into the register
     */
    // uint32_t* temp = *pClkCtrlReg; 	// temp = the value of pClkCtrlReg | read
    // temp = temp | 0x08; 			// lower 16 bits: 0000 0000 0000 1000 -> 0x08 | modify
    // *pClkCtrlReg = temp;			// write back

    // Can also be written as: *pClkCtrlReg = *ClkCtrlReg | 0x08;
    // C shorthand notation: *pClkCtrlReg |= 0x08;	// enables GPIOD

// USING LEFT/RIGHT SHIFT SETTING 3RD BIT POSITION FOR RCC_AHB1ENR
    *pClkCtrlReg |= 1 << 3;

    /* To change the 24th and 25th bit positions in GPIOx_MODER, clear the positions first
     * then set to correct values (01 for general purpose output)
     */
    // *pPortDModeReg &= 0xFCFFFFFF; 	// CLEAR
    // *pPortDModeReg |= 0x01000000;	// SET

// USING LEFT/RIGHT SHIFT CLEARING AND SETTING 24TH AND 25TH BIT POSITION IN GPIOD_MODER
    *pPortDModeReg &= ~(3 << 30);		// 0011 is 3
    *pPortDModeReg |= 1 << 30;

    /* Change the 12th bit position in GPIOx_ODR to turn LED on
     */
    // *pPortDOutReg |= 0x1000;

// USING LEFT/RIGHT SHIFT SETTING 12TH BIT ON GPIOD_ODR
    *pPortDOutReg |= 1 << 15;

    while(1);
}
