/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
 * Decode a given 32bit packet information
 * | ADDR_MODE | SHORT_ADDR |    LONG_ADDR    |  SENSOR  | BAT |      PAYLOAD      | STATUS | CRC |
 * | 1 byte    | 2 bytes    | 8 bytes		  | 3 bytes  | 3   | 12 bytes		   | 1 byte | 2   |
 */

/*
 * Struct modified with union and struct to avoid manually setting and typcasting values
 */

union Packet {
	uint32_t packetValue;	// consumes 4 bytes, but will be overwritten by user input

	struct {
		uint32_t 	crc			:2;
		uint32_t 	status		:1;
		uint32_t 	payload		:12;
		uint32_t 	bat			:3;
		uint32_t	sensor		:3;
		uint32_t	longAddr	:8;
		uint32_t	shortAddr	:2;
		uint32_t	addrMode	:1;
	} packetFields;
};

int main(void)
{
	union Packet packet;

	// User input packet value in hex
	printf("Enter the 32bit packet value: ");
	scanf("%lX", &packet.packetValue);

	// Printing packet values
	printf("crc 			:%x", packet.packetFields.crc);
	printf("status 			:%x", packet.packetFields.status);
	printf("payload 		:%x", packet.packetFields.payload);
	printf("bat 			:%x", packet.packetFields.bat);
	printf("sensor			:%x", packet.packetFields.sensor);
	printf("longAddr		:%x", packet.packetFields.longAddr);
	printf("shortAddr		:%x", packet.packetFields.shortAddr);
	printf("addrMode		:%x", packet.packetFields.addrMode);

    /* Loop forever */
	for(;;);
}
