/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void wait(void);
void swap(int32_t *array1, int32_t *array2, int32_t arraySize1, int32_t arraySize2);
void printArray(int32_t *array, int32_t arraySize);

int main(void)
{
	int32_t arraySize1, arraySize2;

	printf("Array Swapping Program\n");

	printf("Enter no of elements of Array-1 and Array-2: ");
	scanf("%ld %ld\n", &arraySize1, &arraySize2);

	if(arraySize1 < 0 || arraySize2 < 0) {
		printf("Number of elements cannot be negative");
		wait();
		return 0;
	}

	int32_t array1[arraySize1];
	int32_t array2[arraySize2];

	for(uint8_t i = 0; i < arraySize1; i++) {
		printf("Enter element %u of Array-1: ", i);
		scanf("%ld\n", &array1[i]);
	}

	for(uint8_t i = 0; i < arraySize2; i++) {
		printf("Enter element %u of Array-2: ", i);
		scanf("%ld\n", &array2[i]);
	}

	printf("Contents of array before swap\n");
	printArray(array1, arraySize1);
	printArray(array2, arraySize2);

	swap(array1, array2, arraySize1, arraySize2);

	printf("Contents of array after swap\n");
	printArray(array1, arraySize1);
	printArray(array2, arraySize2);
}

void wait(void) {

}

void printArray(int32_t *array, int32_t arraySize) {
	for(uint8_t i = 0; i < arraySize; i++) {
		printf("%ld\t", array[i]);
	}

	printf("\n");
}

void swap(int32_t *array1, int32_t *array2, int32_t arraySize1, int32_t arraySize2) {
	// SWAP
	uint32_t temp;

	if(arraySize1 > arraySize2) {
		for(uint8_t i = 0; i < arraySize2; i++) {
			temp = array1[i];
			array1[i] = array2[i];
			array2[i] = temp;
		}
	} else {
		for(uint8_t i = 0; i < arraySize1; i++) {
			temp = array1[i];
			array1[i] = array2[i];
			array2[i] = temp;
		}
	}
}
