/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
 * Decode a given 32bit packet information
 * | ADDR_MODE | SHORT_ADDR |    LONG_ADDR    |  SENSOR  | BAT |      PAYLOAD      | STATUS | CRC |
 * | 1 byte    | 2 bytes    | 8 bytes		  | 3 bytes  | 3   | 12 bytes		   | 1 byte | 2   |
 */

/*
 * Struct changed to use bit fields, minimizing memory consumption from 10 bytes to 4 bytes
 */

struct Packet {
	uint32_t 	crc			:2;
	uint32_t 	status		:1;
	uint32_t 	payload		:12;
	uint32_t 	bat			:3;
	uint32_t	sensor		:3;
	uint32_t	longAddr	:8;
	uint32_t	shortAddr	:2;
	uint32_t	addrMode	:1;
};

int main(void)
{
	uint32_t packetValue;

	// User input packet value in hex
	printf("Enter the 32bit packet value: ");
	scanf("%lX", &packetValue);

	struct Packet packet;

	packet.crc 			= (uint8_t) (packetValue & 0x3);			// 0x3 = 11
	packet.status 		= (uint8_t) ((packetValue >> 2) & 0x1); 	// right shift crc value out
	packet.payload 		= (uint16_t) ((packetValue >> 3) & 0xFFFF);
	packet.bat 			= (uint8_t) ((packetValue >> 15) & 0x7);
	packet.sensor		= (uint8_t) ((packetValue >> 18) & 0x7);
	packet.longAddr		= (uint8_t) ((packetValue >> 21) & 0xFF);
	packet.shortAddr	= (uint8_t) ((packetValue >> 29) & 0x3);
	packet.addrMode		= (uint8_t) ((packetValue >> 31) & 0x1);

	// Printing packet values
	printf("crc 			:%x", packet.crc);
	printf("status 			:%x", packet.status);
	printf("payload 		:%x", packet.payload);
	printf("bat 			:%x", packet.bat);
	printf("sensor			:%x", packet.sensor);
	printf("longAddr		:%x", packet.longAddr);
	printf("shortAddr		:%x", packet.shortAddr);
	printf("addrMode		:%x", packet.addrMode);

    /* Loop forever */
	for(;;);
}
