/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// Manual LED (GPIOD12) toggle using GND and VCC connected to GPIOA0

	// Assignment --------------------------------------------------------
	// Addresses + offset
	// AHB1: 			0x40023800
	// 		_ENR:					+ 0x30	(Port A: bit 0, Port D: bit 3)
	// GPIOA: 			0x40020000
	// 		_MODER:					+ 0x00	(bit 0 & 1)
	// 		_IDR:					+ 0x10	(bit 0)
	// GPIOD:			0x40020C00
	//		_MODER:					+ 0x00	(bit 24 & 25)
	//		_ODR:					+ 0x14	(bit 12)

	// since pointers below are accessing memory-mapped peripheral registers,
	// volatile qualifier should be used

	uint32_t volatile *pClkCtrlReg = 	(uint32_t*) (0x40023800 + 0x30);
	uint32_t volatile *pPortAModeReg = 	(uint32_t*) (0x40020000 + 0x00),
						*pPortAInReg = 	(uint32_t*) (0x40020000 + 0x10);
	uint32_t volatile *pPortDModeReg = 	(uint32_t*) (0x40020C00 + 0x00),
						*pPortDOutReg = (uint32_t*) (0x40020C00 + 0x14);

	// Configuration -----------------------------------------------------
	// Enable clock for Port A and D
	*pClkCtrlReg |= 1 << 0;
	*pClkCtrlReg |= 1 << 3;

	// SET mode for Port A to input
	*pPortAModeReg &= ~(3); 		// CLEAR / SET 0 and 1 to 00

	// SET mode for Port D to output
	*pPortDModeReg &= ~(3 << 24); 	// CLEAR
	*pPortDModeReg |= 1 << 24;		// SET 24 and 25 to 01

	// Logic -------------------------------------------------------------
	while(1) {
		// Status of GPIOA0
		// Zeros all other bits other than the desired bit position
		uint8_t pinStatus = (uint8_t) (*pPortAInReg & 0x1);

		// Read pPortAInReg bit position 0
		if(pinStatus) {
			// Turn light on
			*pPortDOutReg |= 1 << 12;
		} else {
			// Turn light off
			*pPortDOutReg &= ~(1 << 12);
		}
	}
}
